# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlantConcat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(784, 455)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dirInput = QtWidgets.QLineEdit(self.tab)
        self.dirInput.setObjectName("dirInput")
        self.gridLayout_2.addWidget(self.dirInput, 0, 1, 1, 1)
        self.selectDirBtn = QtWidgets.QPushButton(self.tab)
        self.selectDirBtn.setObjectName("selectDirBtn")
        self.gridLayout_2.addWidget(self.selectDirBtn, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.startBtn = QtWidgets.QPushButton(self.tab)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_2.addWidget(self.startBtn, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.configbox = QtWidgets.QWidget()
        self.configbox.setObjectName("configbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.configbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.xmlConfigInput = QtWidgets.QLineEdit(self.configbox)
        self.xmlConfigInput.setObjectName("xmlConfigInput")
        self.gridLayout_3.addWidget(self.xmlConfigInput, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.configbox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.configbox, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.logBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.logBrowser.setObjectName("logBrowser")
        self.verticalLayout_2.addWidget(self.logBrowser)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(mainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionmapping = QtWidgets.QAction(mainWindow)
        self.actionmapping.setObjectName("actionmapping")
        self.actionOpenMappingFile = QtWidgets.QAction(mainWindow)
        self.actionOpenMappingFile.setObjectName("actionOpenMappingFile")

        self.retranslateUi(mainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "BT100FY Controller"))
        self.selectDirBtn.setText(_translate("mainWindow", "选择文件夹"))
        self.label.setText(_translate("mainWindow", "   输入文件： "))
        self.startBtn.setText(_translate("mainWindow", "开始"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("mainWindow", "植物图片提取"))
        self.xmlConfigInput.setText(_translate("mainWindow", "BG202388-42D.xml"))
        self.label_2.setText(_translate("mainWindow", "  切割位置配置文件：  "))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.configbox), _translate("mainWindow", "配置文件"))
        self.actionOpenFile.setText(_translate("mainWindow", "OpenFile"))
        self.actionmapping.setText(_translate("mainWindow", "mapping"))
        self.actionOpenMappingFile.setText(_translate("mainWindow", "OpenMappingFile"))
